#!/usr/bin/perl

use CGI;
use DBI;

sub get_locations {
    my $c = CGI->new;
    my $dbh = DBI->connect("DBI:mysql:database=piperpalcom02;host=piperpalcom02.mysql.domeneshop.no", "piperpalcom02", "xxxxxxxx", {'RaiseError' => 1});
    print "<?xml version='1.0'?>\n";
    print "<?xml-stylesheet type='text/xsl' href='/piperpal.xsl'?>\n";
    print "<piperpal version='10.0'>\n";
#    $dbh->do ("SELECT DISTINCT email,name,glat,glon,location,modified,created,service,paid FROM piperpal WHERE modified < NOW() AND created > NOW();");
    my $sth = $dbh->prepare ("SELECT DISTINCT email,name,glat,glon,location,modified,created,service,paid FROM piperpal WHERE modified < NOW() and created > NOW() and paid > 0 ORDER by name;");
    $sth->execute();
    while (my $ref = $sth->fetchrow_hashref()) {
                print "<location src='http://api.piperpal.com/location' service='" . $ref->{'service'} . "' name='" . $ref->{'name'} . "' lat='" . $ref->{'glat'} . "' lon='" . $ref->{'glon'} . "' href='" . $ref->{'location'} . "' notbefore='" . $ref->{'modified'} . "' notafter='" . $ref->{'created'} . "' paid='" . $ref->{'paid'} . "'>" . $ref->{'name'} . "</location>\n";
    }
    $sth->finish();
    $dbh->disconnect();
    print "</piperpal>\n";
    return;
}
&get_locations;
